name: flutter_clean_architecture
description: A Flutter project to demonestrate clean architecture implementation.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.4
  equatable: ^2.0.3
  flutter_bloc: ^8.0.1
  get_it: ^7.2.0
  remote:
    path: ./remote/
  cache:
    path: ./cache/
  data:
    path: ./data/
  domain:
    path: ./domain/

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: ^9.0.2
  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true
