name: domain
description: A Flutter package to contain the domain layer.
version: 0.0.1
publish_to: 'none'

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  injectable: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.7.0
  build_runner: ^2.5.4
  flutter_lints: ^6.0.0
  mockito: ^5.4.6

flutter:
