name: domain
description: A Flutter package to contain the domain layer.
version: 0.0.1
publish_to: 'none'

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  injectable: ^1.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  injectable_generator: ^1.5.3
  build_runner: ^2.2.0
  flutter_lints: ^2.0.1
  mockito: ^5.2.0

flutter:
