name: domain
description: A Flutter package to contain the domain layer.
version: 0.0.1
publish_to: 'none'

environment:
  sdk: ">=2.15.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.7
  flutter_lints: ^1.0.4
  mockito: ^5.0.17

flutter:
