name: remote
description: A Flutter package to contain remote related logic.
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  data:
    path: ../data/
  dio: ^5.8.0+1
  injectable: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.7.0
  build_runner: ^2.5.4
  flutter_lints: ^6.0.0
  mockito: ^5.4.6

flutter:
