// Mocks generated by Mockito 5.0.17 from annotations
// in remote/test/src/articles_remote_repository_impl_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i6;

import 'package:data/data.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:remote/src/api/articles_service.dart' as _i5;
import 'package:remote/src/api/endpoint_provider.dart' as _i2;
import 'package:remote/src/mapper/articles_entity_mapper.dart' as _i7;
import 'package:remote/src/models/article/article_model.dart' as _i8;
import 'package:remote/src/models/article/articles_response_model.dart' as _i3;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeEndpointProvider_0 extends _i1.Fake implements _i2.EndpointProvider {
}

class _FakeArticlesResponseModel_1 extends _i1.Fake
    implements _i3.ArticlesResponseModel {}

class _FakeArticlesEntity_2 extends _i1.Fake implements _i4.ArticlesEntity {}

/// A class which mocks [ArticlesService].
///
/// See the documentation for Mockito's code generation for more information.
class MockArticlesService extends _i1.Mock implements _i5.ArticlesService {
  MockArticlesService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.EndpointProvider get endpointProvider =>
      (super.noSuchMethod(Invocation.getter(#endpointProvider),
          returnValue: _FakeEndpointProvider_0()) as _i2.EndpointProvider);
  @override
  _i6.Future<_i3.ArticlesResponseModel> getMostEmailedArticles() =>
      (super.noSuchMethod(Invocation.method(#getMostEmailedArticles, []),
              returnValue: Future<_i3.ArticlesResponseModel>.value(
                  _FakeArticlesResponseModel_1()))
          as _i6.Future<_i3.ArticlesResponseModel>);
  @override
  _i6.Future<_i3.ArticlesResponseModel> getMostSharedArticles() =>
      (super.noSuchMethod(Invocation.method(#getMostSharedArticles, []),
              returnValue: Future<_i3.ArticlesResponseModel>.value(
                  _FakeArticlesResponseModel_1()))
          as _i6.Future<_i3.ArticlesResponseModel>);
  @override
  _i6.Future<_i3.ArticlesResponseModel> getMostViewedArticles() =>
      (super.noSuchMethod(Invocation.method(#getMostViewedArticles, []),
              returnValue: Future<_i3.ArticlesResponseModel>.value(
                  _FakeArticlesResponseModel_1()))
          as _i6.Future<_i3.ArticlesResponseModel>);
}

/// A class which mocks [ArticlesEntityMapper].
///
/// See the documentation for Mockito's code generation for more information.
class MockArticlesEntityMapper extends _i1.Mock
    implements _i7.ArticlesEntityMapper {
  MockArticlesEntityMapper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.ArticlesEntity mapFromModel(_i8.ArticleModel? articleModel) =>
      (super.noSuchMethod(Invocation.method(#mapFromModel, [articleModel]),
          returnValue: _FakeArticlesEntity_2()) as _i4.ArticlesEntity);
}
